<?php

namespace App\Http\Controllers;

use App\Models\Task;
use App\Models\Project;
use App\Models\User;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Carbon\Carbon;
use Illuminate\Support\Facades\Response;

class TaskController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();
        // Check for specific roles or the 'manage tasks' permission
        $isPrivileged = $user->hasPermissionTo('view tasks') || 
                        $user->roles->whereIn('name', ['Super Admin', 'Admin', 'HR', 'manager', 'team lead', 'Manager', 'Team Lead'])->count() > 0;

        $tasksQuery = Task::with('project', 'assignee', 'creator', 'comments.user');

        // Search
        if ($request->search) {
            $tasksQuery->where('title', 'like', "%{$request->search}%");
        }

        // Date Filters
        $this->applyFilters($tasksQuery, $request);

        // Security: Stricter Privacy - Everyone sees only their own tasks (assigned to them)
        // OR tasks they created (to manage those they haven't assigned yet)
        $tasksQuery->where(function($q) use ($user) {
            $q->where('assigned_to', $user->id)
              ->orWhere('created_by', $user->id);
        });

        // Performance Calculation Logic
        $performanceData = $this->calculatePerformance($user, $request, $isPrivileged);

        $tasks = $tasksQuery->orderBy('id', 'desc')->paginate(10)->withQueryString();

        $projects = Project::all();
        $users = User::whereHas('roles', fn($q) => $q->whereIn('name', ['Employee', 'Admin', 'Super Admin', 'manager', 'team lead', 'Manager', 'Team Lead', 'HR', 'employee', 'admin', 'super admin', 'hr']))->get();

        return Inertia::render('Tasks/Index', [
            'tasks' => $tasks,
            'projects' => $projects,
            'users' => $users,
            'performance' => $performanceData['score'],
            'performanceLabel' => $performanceData['label'],
            'filters' => $request->only(['search', 'filter_type', 'start_date', 'end_date'])
        ]);
    }

    public function export(Request $request)
    {
        $user = $request->user();
        $isPrivileged = $user->roles->whereIn('name', ['Super Admin', 'Admin', 'HR', 'manager', 'team lead', 'Manager', 'Team Lead', 'admin', 'super admin', 'hr', 'superadmin', 'Superadmin'])->count() > 0;

        $tasksQuery = Task::with('project', 'assignee', 'creator');
        $this->applyFilters($tasksQuery, $request);

        // Security: Employees only see their own tasks
        if (!$isPrivileged) {
            $tasksQuery->where('assigned_to', $user->id);
        }

        $tasks = $tasksQuery->get();
        $stats = [
            'total' => $tasks->count(),
            'completed' => $tasks->where('status', 'completed')->count(),
            'pending' => $tasks->where('status', 'pending')->count(),
            'in_progress' => $tasks->where('status', 'in_progress')->count(),
            'period' => strtoupper($request->filter_type ?? 'All Time'),
            'user' => $user->name
        ];

        if ($request->format === 'doc') {
            return $this->exportToDoc($tasks, $stats);
        }

        return $this->exportToExcel($tasks, $stats);
    }

    protected function exportToExcel($tasks, $stats)
    {
        $headers = [
            "Content-type" => "text/csv",
            "Content-Disposition" => "attachment; filename=tasks_report_" . date('Y-m-d') . ".csv",
            "Pragma" => "no-cache",
            "Cache-Control" => "must-revalidate, post-check=0, pre-check=0",
            "Expires" => "0"
        ];

        $callback = function () use ($tasks, $stats) {
            $file = fopen('php://output', 'w');
            
            // Header Section
            fputcsv($file, ['TASK MANAGEMENT REPORT']);
            fputcsv($file, ['Report Period:', $stats['period']]);
            fputcsv($file, ['Generated By:', $stats['user']]);
            fputcsv($file, ['Date:', date('Y-m-d H:i')]);
            fputcsv($file, ['Summary:']);
            fputcsv($file, ['Total Tasks', 'Completed', 'In Progress', 'Pending']);
            fputcsv($file, [$stats['total'], $stats['completed'], $stats['in_progress'], $stats['pending']]);
            fputcsv($file, []); // Spacer

            // Data Table Headers
            fputcsv($file, ['ID', 'Title', 'Project', 'Assigned To', 'Priority', 'Status', 'Due Date', 'Created At']);

            foreach ($tasks as $task) {
                fputcsv($file, [
                    $task->id,
                    $task->title,
                    $task->project ? $task->project->name : 'N/A',
                    $task->assignee ? $task->assignee->name : 'Unassigned',
                    strtoupper($task->priority),
                    strtoupper($task->status),
                    $task->due_date ?? 'N/A',
                    $task->created_at->format('Y-m-d')
                ]);
            }
            fclose($file);
        };

        return Response::stream($callback, 200, $headers);
    }

    protected function exportToDoc($tasks, $stats)
    {
        $filename = "tasks_report_" . date('Y-m-d') . ".doc";
        
        $headers = [
            "Content-type" => "application/vnd.ms-word",
            "Content-Disposition" => "attachment; filename=$filename",
            "Pragma" => "no-cache",
            "Expires" => "0"
        ];

        $html = "
        <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
        <head><meta charset='utf-8'><title>Professional Task Report</title>
        <style>
            body { font-family: 'Segoe UI', Arial, sans-serif; color: #333; }
            .header { text-align: center; border-bottom: 3px solid #6366f1; padding-bottom: 20px; margin-bottom: 30px; }
            .report-title { font-size: 24pt; font-weight: bold; color: #1e1b4b; margin: 0; }
            .report-meta { font-size: 10pt; color: #666; margin-top: 5px; }
            
            .stats-container { margin-bottom: 30px; width: 100%; border-spacing: 15px; border-collapse: separate; }
            .stat-box { background-color: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 8px; text-align: center; }
            .stat-value { font-size: 18pt; font-weight: bold; color: #6366f1; }
            .stat-label { font-size: 9pt; color: #64748b; text-transform: uppercase; font-weight: bold; }
            
            table { border-collapse: collapse; width: 100%; margin-top: 20px; font-size: 10pt; }
            th { background-color: #6366f1; color: white; padding: 12px 8px; text-align: left; border: 1px solid #4f46e5; }
            td { padding: 10px 8px; border: 1px solid #e2e8f0; }
            tr:nth-child(even) { background-color: #f1f5f9; }
            
            .priority { font-weight: bold; text-transform: uppercase; font-size: 8pt; }
            .status { padding: 4px 8px; border-radius: 4px; font-weight: bold; font-size: 8pt; display: inline-block; }
            
            .footer { margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 10px; font-size: 8pt; color: #94a3b8; text-align: right; }
        </style>
        </head>
        <body>
            <div class='header'>
                <h1 class='report-title'>TASK MANAGEMENT REPORT</h1>
                <div class='report-meta'>
                    <strong>Period:</strong> {$stats['period']} | 
                    <strong>Exported By:</strong> {$stats['user']} | 
                    <strong>Date:</strong> " . date('d M, Y H:i') . "
                </div>
            </div>

            <table class='stats-container'>
                <tr>
                    <td class='stat-box'><div class='stat-value'>{$stats['total']}</div><div class='stat-label'>Total Tasks</div></td>
                    <td class='stat-box'><div class='stat-value'>{$stats['completed']}</div><div class='stat-label'>Completed</div></td>
                    <td class='stat-box'><div class='stat-value'>{$stats['in_progress']}</div><div class='stat-label'>Active</div></td>
                    <td class='stat-box'><div class='stat-value'>{$stats['pending']}</div><div class='stat-label'>Pending</div></td>
                </tr>
            </table>

            <table>
                <thead>
                    <tr>
                        <th width='50'>ID</th>
                        <th>Task Information</th>
                        <th>Project</th>
                        <th>Priority</th>
                        <th width='80'>Status</th>
                        <th width='100'>Deadline</th>
                    </tr>
                </thead>
                <tbody>";

        foreach ($tasks as $task) {
            $html .= "<tr>
                <td style='text-align: center;'>{$task->id}</td>
                <td>
                    <strong>" . htmlspecialchars($task->title) . "</strong><br/>
                    <span style='font-size: 8pt; color: #666;'>" . htmlspecialchars(substr($task->description, 0, 80)) . (strlen($task->description) > 80 ? '...' : '') . "</span>
                </td>
                <td>" . ($task->project ? htmlspecialchars($task->project->name) : 'Independent') . "</td>
                <td class='priority'>" . strtoupper($task->priority) . "</td>
                <td class='status' style='color: " . ($task->status === 'completed' ? '#166534' : ($task->status === 'in_progress' ? '#1e40af' : '#92400e')) . ";'>" . strtoupper($task->status) . "</td>
                <td>" . ($task->due_date ?? 'N/A') . "</td>
            </tr>";
        }

        $html .= "</tbody></table>
            <div class='footer'>
                This is a system generated report from Task Management Dashboard.
            </div>
        </body></html>";

        return Response::make($html, 200, $headers);
    }

    private function applyFilters($query, $request)
    {
        $filter = $request->filter_type ?? 'all';
        $now = Carbon::now();

        if ($filter === 'daily') {
            $query->whereDate('created_at', Carbon::today());
        } elseif ($filter === 'weekly') {
            $query->whereBetween('created_at', [$now->startOfWeek()->toDateTimeString(), $now->endOfWeek()->toDateTimeString()]);
        } elseif ($filter === 'monthly') {
            $query->whereMonth('created_at', $now->month)->whereYear('created_at', $now->year);
        } elseif ($filter === 'custom' && $request->start_date && $request->end_date) {
            $query->whereBetween('created_at', [$request->start_date . ' 00:00:00', $request->end_date . ' 23:59:59']);
        }
    }

    private function calculatePerformance($user, $request, $isPrivileged)
    {
        // For performance, we usually look at the assigned tasks of the current user 
        // OR if admin looks at a specific period

        $perfQuery = Task::query();
        $this->applyFilters($perfQuery, $request);

        if (!$isPrivileged) {
            $perfQuery->where('assigned_to', $user->id);
            $label = "My Performance";
        } else {
            $label = "Team Progress";
        }

        $total = (clone $perfQuery)->count();
        $completed = (clone $perfQuery)->where('status', 'completed')->count();

        $score = $total > 0 ? round(($completed / $total) * 100) : 0;

        return [
            'score' => $score,
            'label' => $label
        ];
    }

    public function store(Request $request)
    {
        $user = $request->user();
        $isPrivileged = $user->hasPermissionTo('create tasks') || 
                        $user->roles->whereIn('name', ['Super Admin', 'Admin', 'HR', 'manager', 'team lead', 'Manager', 'Team Lead'])->count() > 0;

        $request->validate([
            'project_id' => 'required|exists:projects,id',
            'assigned_to' => 'nullable|exists:users,id',
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
            'due_date' => 'nullable|date',
            'priority' => 'required|in:low,medium,high,urgent',
        ]);

        // Security: If not privileged, ALWAYS force assignment to self
        $assignedTo = $request->assigned_to;
        if (!$isPrivileged) {
            $assignedTo = $user->id;
        }

        $task = Task::create([
            'project_id' => $request->project_id,
            'assigned_to' => $assignedTo,
            'title' => $request->title,
            'description' => $request->description,
            'due_date' => $request->due_date,
            'status' => 'pending',
            'priority' => $request->priority,
            'created_by' => $user->id,
        ]);

        // Notify Assignee
        if ($assignedTo) {
            $assignee = User::find($assignedTo);
            if ($assignee) {
                $assignee->notify(new \App\Notifications\TaskAssignedNotification($task));
            }
        }

        return redirect()->back()->with('success', '✅ Task created successfully.');
    }

    public function update(Request $request, Task $task)
    {
        $user = $request->user();
        
        // Only creator can edit
        if ($task->created_by !== $user->id) {
            abort(403, 'Only the creator can edit this task.');
        }

        $isPrivileged = $user->hasPermissionTo('edit tasks') || 
                        $user->roles->whereIn('name', ['Super Admin', 'Admin', 'HR', 'manager', 'team lead', 'Manager', 'Team Lead'])->count() > 0;

        $request->validate([
            'project_id' => 'required|exists:projects,id',
            'assigned_to' => 'nullable|exists:users,id',
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
            'due_date' => 'nullable|date',
            'priority' => 'required|in:low,medium,high,urgent',
        ]);

        $assignedTo = $request->assigned_to;
        if (!$isPrivileged) {
            $assignedTo = $user->id;
        }

        $task->update([
            'project_id' => $request->project_id,
            'assigned_to' => $assignedTo,
            'title' => $request->title,
            'description' => $request->description,
            'due_date' => $request->due_date,
            'priority' => $request->priority,
        ]);

        return redirect()->back()->with('success', '✅ Task updated successfully.');
    }

    public function updateStatus(Request $request, Task $task)
    {
        $request->validate([
            'status' => 'required|in:pending,in_progress,completed'
        ]);

        $task->update(['status' => $request->status]);

        return redirect()->back()->with('success', '✅ Task status updated. Performance metrics recalculated.');
    }

    public function reassign(Request $request, Task $task)
    {
        $user = $request->user();
        $isPrivileged = $user->hasPermissionTo('edit tasks') || 
                        $user->roles->whereIn('name', ['Super Admin', 'Admin', 'manager', 'team lead', 'Manager', 'Team Lead'])->count() > 0;

        if (!$isPrivileged) {
            abort(403);
        }

        $request->validate([
            'assigned_to' => 'required|exists:users,id',
        ]);

        $task->update(['assigned_to' => $request->assigned_to]);

        // Notify New Assignee
        $newAssignee = User::find($request->assigned_to);
        if ($newAssignee) {
            $newAssignee->notify(new \App\Notifications\TaskAssignedNotification($task));
        }

        return redirect()->back()->with('success', '✅ Task successfully reassigned to ' . ($newAssignee->name ?? 'new member') . '.');
    }
}
